# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN yum -y install --disablerepo=epel epel-release && sed -i 's/https:\/\//http:\/\//' /etc/yum.repos.d/epel.repo
RUN yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all
#RUN curl http://slmgtams1064.basis.lan/Amsterdam-PRD-Root-CA.pem > /etc/pki/ca-trust/source/anchors/Amsterdam-Root-CA.pem
#RUN update-ca-trust
