---

- name: Converge
  hosts: all
  vars:
    molecule_test: true
    python2: true
    python3: true
    python_virtualenv:
      - name: ansible27
        label: ansible_current
        packages:
          - ansible==2.7.15
          - ansible-tower-cli==3.3.6
      - name: ansible28
        source: ansible27
        label: ansible_future
        recreate: True
        packages:
          - ansible==2.8.5
          - lxml
  roles:
    - role: ansible-role-python
