---

role_description: |
  Installs python 2 and/or 3 from repository

os_vars_fields:
  - name: platform
    width: 70
  - name: python2
    width: 15
  - name: python3
    width: 15

os_vars:
  - platform: Fedora
    python2: False
    python3: True
  - platform: RedHat7
    python2: True
    python3: False

role_vars_fields:
  - name: variable
    width: 10
  - name: required
    width: 5
  - name: type
    width: 5
  - name: default
    width: 40
  - name: description
    width: 40

role_vars:
  - variable: python_virtualenv_root
    required: no
    type: string
    default: /virtualenv
    description: Base directory where to place virtual environments.  All virtual environments will be placed underneath
  - variable: python_package_install
    required: no
    type: boolean
    default: true
    description: If the Python OS packes should be installed
  - variable: python2
    required: no
    type: boolean
    default: See vars/{@{ ansible_distribution }}.yml
    description: If Python2 should be installed
  - variable: python2_command
    required: no
    type: string
    default: See vars/{@{ ansible_distribution }}.yml
    description: Full path to the python2 executable
  - variable: python2_virtualenv
    required: no
    type: string
    default: See vars/{@{ ansible_distribution }}.yml
    description: Full path to the python2 virtualenv executable
  - variable: python2_packages
    required: no
    type: list
    default: See vars/{@{ ansible_distribution }}.yml
    description: List of packages required to install Python
  - variable: python_virtualenv
    required: no
    type: list
    default: []
    description: List of virtual environments to create
  - variable: python3
    required: no
    type: boolean
    default: See vars/{@{ ansible_distribution }}.yml
    description: If Python3 should be installed
  - variable: python3_command
    required: no
    type: string
    default: See vars/{@{ ansible_distribution }}.yml
    description: Full path to the python3 executable
  - variable: python3_virtualenv
    required: no
    type: string
    default: See vars/{@{ ansible_distribution }}.yml
    description: Full path to the python3 virtualenv executable
  - variable: python3_packages
    required: no
    type: list
    default: See vars/{@{ ansible_distribution }}.yml
    description: List of packages required to install Python
  - variable: python_virtualenv
    required: no
    type: list
    default: []
    description: List of virtual environments to create
  - variable: name
    required: yes
    type: string
    default: 'N/A'
    description: Name of the virtual environment.
    ident: 2
  - variable: path
    required: no
    type: string
    default: "{@{ python_virtualenv_root }}/python[23]/{@{ name }}"
    description: Full path to the virtual env
    ident: 2
  - variable: packages
    required: no
    type: list
    default: []
    description: List of pip packages to install
    ident: 2
  - variable: site_packages
    required: False
    type: boolean
    default: False
    description: If Python site packages should be made available to the virtualenv
    ident: 2
  - variable: pip_upgrade
    required: no
    type: boolean
    default: True
    description: Upgrade pip inside virtualenv
    ident: 2
  - variable: source
    required: False
    type: string
    default: 'N/A'
    description: Name of virtual environment to clone to new
    ident: 2
  - variable: label
    required: False
    type: string
    default: 'N/A'
    description: symlink to create to point to this virtualenv
    ident: 2
  - variable: recreate
    required: False
    type: boolean
    default: False
    description: Force virtualenv to be recreated
    ident: 2

role_examples:
  - description: |
      + Install Python2
      + Install Python3
      + Setup virtualenv 'ansible27' from scratch
      + Setup virtualenv 'ansible28' by cloning it from 'ansible27'
    code: |-
      - hosts: all
        vars:
          python2: true
          python3: true
          python_virtualenv:
            - name: ansible27
              label: ansible_current
              packages:
                - ansible==2.7.15
                - ansible-tower-cli==3.3.6
            - name: ansible28
              source: ansible27
              label: ansible_future
              packages:
                - ansible==2.8.5
                - lxml
        roles:
          - {{ role }}
