---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Move and symlink virtual environment location
  include_tasks: link.yml
  when: python_virtualenv_data is defined

- name: Including 'python2'
  include_tasks: python.yml
  vars:
    python: python2
  when: python2|bool

- name: Including 'python3'
  include_tasks: python.yml
  vars:
    python: python3
  when: python3|bool

- name: Including 'python38'
  include_tasks: python.yml
  vars:
    python: python38
  when: python38|bool

- name: Upgrading pip (site-packages)
  include_tasks: pip.yml
  when: pip_upgrade|bool

- name: Install python from source
  include_tasks: source.yml
  when: python_from_source

- name: Setup virtual environments
  include_tasks: venvs.yml
  when: python_virtualenvs is defined
