---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install python
  ansible.builtin.include_tasks: install.yml
  when: not python_virtualenv_only | bool

- name: Setup virtual environments
  ansible.builtin.include_tasks: venvs.yml
  when: python_virtualenvs is defined and python_virtualenvs | length > 0
