---

- name: Include distro specific settings
  include_vars: vars/{{ ansible_distribution }}.yml

- name: Move and symlink virtual environment location
  include_tasks: link.yml
  when: python_virtualenv_data is defined

- name: Including 'python2.yml'
  include: python.yml
  vars:
    python: python2
  when: python2|bool

- name: Including 'python3.yml'
  include: python.yml
  vars:
    python: python3
  when: python3|bool
