---

- name: Load variables based on OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Reset all variables that require resetting  # noqa var-naming
  set_fact:
    "{{ item }}": "{{ vars['reset_vars'][item] }}"
  loop: "{{ (reset_vars|default({})) | dict2items | json_query('[].key') }}"
  loop_control:
    label:
      - "{{ item }}"

- name: Show debug settings
  debug:
    msg:
      python2: "{{ python2 }}"
      python3: "{{ python3 }}"
      python38: "{{ python38 | default('N/A') }}"
      python39: "{{ python39 | default('N/A') }}"
      python_virtualenvs: "{{ python_virtualenvs }}"
#    verbosity: 1

- name: Move and symlink virtual environment location
  include_tasks: link.yml
  when:
    - python_virtualenv_data is defined
    - python_virtualenv_data|length > 0

- name: Including 'python2'
  include_tasks: python.yml
  vars:
    python: python2
  when: python2|bool

- name: Including 'python3'
  include_tasks: python.yml
  vars:
    python: python3
  when: python3|bool

- name: Including 'python38'
  include_tasks: python.yml
  vars:
    python: python38
  when: python38 is defined and python38|bool

- name: Including 'python39'
  include_tasks: python.yml
  vars:
    python: python39
  when: python39 is defined and python39|bool

- name: Upgrading pip (site-packages)
  include_tasks: pip.yml
  when: pip_upgrade|bool

- name: Install python from source
  include_tasks: source.yml
  when: python_from_source is defined and python_from_source|bool

- name: Setup virtual environments
  include_tasks: venvs.yml
  when: python_virtualenvs is defined and python_virtualenvs|length > 0
