---

- name: Converge
  hosts: all
  vars:
    python2: false
    python3: true
    python_virtualenv_root: /tmp/venv
    python_virtualenvs:
      - name: sample
        recreate: false
        python: /usr/bin/python3
        site_packages: false
        packages:
          - lxml
          - dnspython
  tasks:
    - name: Include role 'ansible-role-python'
      include_role:
        name: ansible-role-python
