---

- name: Converge pre playbook
  ansible.builtin.import_playbook: converge-pre.yml
  when: molecule_converge_pre is undefined or molecule_converge_pre | bool

- name: Converge
  hosts: all
  become: "yes"
  vars:
    python_package_install_optional: True
    python_virtualenv_root: /tmp/venv
    python_virtualenvs: [{'name': 'sample', 'packages': ['dnspython'], 'packages_rm': ['selinux'], 'python': '/usr/bin/python3', 'recreate': False, 'site_packages': False, 'user': 'sample', 'pip_upgrade': True}]
  tasks:
    - name: Include role 'ansible-role-python'
      ansible.builtin.include_role:
        name: ansible-role-python
