---

- ansible.builtin.import_playbook: converge-pre.yml

- name: Converge
  hosts: all
  become: "{{ molecule['converge']['become'] | default('yes') }}"
  vars:
    python2: False
    python3: True
    python_package_install_optional: True
    python_virtualenv_root: /tmp/venv
    python_virtualenvs: [{'name': 'sample', 'packages': ['dnspython'], 'python': '/usr/bin/python3', 'recreate': False, 'site_packages': False, 'user': 'sample'}]
  tasks:
    - name: Include role 'ansible-role-python'
      ansible.builtin.include_role:
        name: ansible-role-python
