---
- name: Converge
  hosts: all
  vars:
    python_from_source: true
    python_virtualenv_root: /tmp/venv
    python_virtualenvs:
      - name: ansible47
        recreate: false
        python: "{{ '/usr/local/bin/python3.8' if ansible_os_family == 'RedHat' else '/usr/bin/python3' }}"
        site_packages: false
        packages:
          - lxml
          - dnspython

  tasks:

    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 1
      become: yes
      when: ansible_os_family == 'Debian'

    - name: "Include ansible-role-python"
      include_role:
        name: "ansible-role-python"
